language: node_js

node_js:
  - 10
  - 8

after_success:
  - if [[ $TRAVIS_NODE_VERSION == "10" ]]; then npm i -g c8 codecov; fi
  - if [[ $TRAVIS_NODE_VERSION == "10" ]]; then c8 --exclude=tests --reporter=lcovonly npm test; fi
  - if [[ $TRAVIS_NODE_VERSION == "10" ]]; then codecov; fi
