language: node_js

node_js:
  - 10
  - 8

after_success:
  - if [[ $TRAVIS_NODE_VERSION == "10" ]]; then npm i -g nyc codecov; fi
  - if [[ $TRAVIS_NODE_VERSION == "10" ]]; then nyc -r=text-lcov --exclude=tests npm test; fi
  - if [[ $TRAVIS_NODE_VERSION == "10" ]]; then codecov; fi
